#!/bin/bash
#SBATCH --job-name=featureCounts                      # Job name
#SBATCH --output=/usr/local/scratch/fdumetz/Leishmania/featureCounts.out   # Standard output log
#SBATCH --error=/usr/local/scratch/fdumetz/Leishmania/featureCounts.err    # Standard error log
#SBATCH --mail-type=BEGIN,END --mail-user=fdumetz@som.umaryland.edu
#SBATCH --cpus-per-task=32				# Number of CPUs per task
#SBATCH --mem=30G                                        # Memory per node
#SBATCH --partition=all
# Using featureCount to generate a count table

# Paths to resources
ANNOTATION="/usr/local/scratch/fdumetz/Leishmania/Ld1S_stg_filtered.transdecoder.genome.gtf"
OUTPUT="Leish_PvCount.txt"
THREADS=32

# Collect all BAM files from multiple directories
BAM_FILES=$(find /usr/local/scratch/fdumetz/Leishmania -name "*.bam")

# Run featureCounts
featureCounts -a $ANNOTATION \
              -o $OUTPUT \
              -t exon \
              -g gene_id \
              -T $THREADS \
              -s 0 \
              -O \
              -M \
              --fraction \
              $BAM_FILES
